### PR TITLE
Alternative "no app" facebook share link.

### PR DESCRIPTION
**Pull request by Johannestegner**

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request. Please update the original example instead of adding an extra. When you've done that I'll merge this pull request.

For the sake of open source productivity, please always add a description to your future issues and pull requests. Thanks.

**Comment by Johannestegner** [comment]
Oh yes, sorry for no description of the PR.  

I think it might be a good idea to have both of the share links, seeing the one with the `app_id` is shared through a specific app, giving a bit nicer share dialog from my understanding.  

The `app_id` version is called `Share Dialog`, while the none-app-id version can be found under `Share button` and can be found under `plugins` in the docs: https://developers.facebook.com/docs/plugins/share-button/

I noticed that I omitted the docs link to the share-button, which I will add right away. Let me know how you wish me to proceed with saving/discarding either of the links!

**Comment by vinkla** [comment]
TBH, both examples are basically the same. We note what parameters the URL accepts and it should be fine. Please remove the share dialog completely and lets just keep the share button.

**Comment by Johannestegner** [comment]
Just bumping/reminding about this PR, want me to close it rather than merging? :)

**Comment by vinkla** [comment]
LGTM, thanks!

**Pull request merged**
